In [1]:
#Linear Regression
#Equation: Y= mX + C
#Y = Target
#C = Intercept (the point on Y-axis where the line touches)
#m = Coeff or Slope
#X = Feature

In [2]:
# Multiple Variables
#Equation = m1x1 + m2x2 + m3x3 + ....+ C

In [3]:
#For single Feature: Y1= m1X1 + C1

# Y2 = m2x2+c2
#Y3 = m3x3+c3

#Y1+Y2+Y3 = m1X1 + C1 + m2x2+c2 + m3x3+c3
#Y = Y1+Y2+Y3
#Y = m1x1 + m2x2 + m3x3 + ....+ C

In [12]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

In [5]:
feature1 = np.array([1,2,3,4,5,6,7,8,9])
feature2 = np.array([2,3,4,5,6,7,8,9,10])
target = np.array([2,14,6,8,11,12,15,16,30])

In [7]:
data_dict = {
    "feature1": feature1,
    "feature2":feature2,
    "target":target
}

In [10]:
df = pd.DataFrame(data_dict)

In [11]:
df

feature1  feature2  target
0         1         2       2
1         2         3      14
2         3         4       6
3         4         5       8
4         5         6      11
5         6         7      12
6         7         8      15
7         8         9      16
8         9        10      30

In [13]:
Lreg = LinearRegression()

In [16]:
features = df[["feature1","feature2"]]

In [17]:
features

feature1  feature2
0         1         2
1         2         3
2         3         4
3         4         5
4         5         6
5         6         7
6         7         8
7         8         9
8         9        10

In [18]:
target = df[["target"]]

In [19]:
target

target
0       2
1      14
2       6
3       8
4      11
5      12
6      15
7      16
8      30

In [22]:
print(features.shape)
print(target.shape)

(9, 2)
(9, 1)


In [23]:
Lreg.fit(features, target)

LinearRegression()

In [24]:
Lreg.coef_

array([[1.16666667, 1.16666667]])

In [25]:
Lreg.intercept_

array([-0.16666667])

In [26]:
# Y = m1x1 + m2x2 + C

## Metrics

In [27]:
from sklearn.metrics import accuracy_score, mean_absolute_error, mean_squared_error

In [30]:
test_features = [1,2,3,4,5,6,7,8,9,10]
test_target = [1.1,2,300,4,5,6,7,8,9,100]

In [31]:
accuracy_score(test_features, test_target)

0.9

In [32]:
#accuracy = True Cases / Total Cases

In [41]:
test_features = [1,2,3,4,5,6,7,8,9,10]
test_target = [100,2,3,4,5,6,7,8,9,10]

In [40]:
mean_squared_error(test_features, test_target)

1020.1

#### Prediction with Metrics

In [88]:
feature = np.array([1,2,3,4,5,6,7,8,9,10])
target = np.array([2,4,6,8,10,12,14,16,18,22])

In [89]:
feature = feature.reshape(-1,1)

In [90]:
Lreg = LinearRegression()

In [91]:
Lreg.fit(feature,target)

LinearRegression()

In [92]:
Lreg.coef_

array([2.10909091])

In [93]:
Lreg.intercept_

-0.3999999999999968

In [94]:
Lreg.predict([[11],[20],[33]])

array([22.8       , 41.78181818, 69.2       ])

In [97]:
feature = np.array([1,2,3,4,5,6,7,8,9,10])
target = np.array([2,4,6,8,10,12,14,16,18,22])

In [98]:
data_dict = {
    "feature": feature,
    "target":target
}

In [99]:
df = pd.DataFrame(data_dict)

In [100]:
df

feature  target
0        1       2
1        2       4
2        3       6
3        4       8
4        5      10
5        6      12
6        7      14
7        8      16
8        9      18
9       10      22

In [101]:
from sklearn.model_selection import train_test_split

In [102]:
# name = "Miral"
# age = 50
name, age  = "Miral", 50

In [103]:
x_train, x_test, y_train, y_test = train_test_split(df['feature'], df['target'], test_size=0.2)

In [104]:
x_train.shape

(8,)

In [105]:
x_train

7     8
3     4
4     5
2     3
5     6
9    10
1     2
0     1
Name: feature, dtype: int32

In [106]:
x_test

8    9
6    7
Name: feature, dtype: int32

In [107]:
y_train

7    16
3     8
4    10
2     6
5    12
9    22
1     4
0     2
Name: target, dtype: int32

In [108]:
y_test

8    18
6    14
Name: target, dtype: int32

In [109]:
reg = LinearRegression()

In [110]:
type(x_train)

pandas.core.series.Series

In [111]:
type(x_train.values)

numpy.ndarray

In [112]:
reg.fit(x_train.values.reshape(-1,1), y_train)

LinearRegression()

In [113]:
reg.coef_

array([2.15799615])

In [114]:
y_pred = reg.predict(x_test.values.reshape(-1,1))

In [118]:
y_pred

array([18.9017341 , 14.58574181])

In [119]:
mean_squared_error(y_pred, y_test)

0.5781089318795198