In [5]:
# Use of CONTINUE statement

In [1]:
list_of_people = ['Dev','Jai','Lex','Dhyan']

In [2]:
for i in list_of_people:
    if i=='Lex':
        break
    print(i)

Dev
Jai


In [3]:
for i in list_of_people:
    if i=='Lex':
        continue
    print(i)

Dev
Jai
Dhyan


In [4]:
# Num py

In [8]:
import numpy

In [9]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
arr = numpy.array([1,2,3,4,5])

In [11]:
type(arr)

numpy.ndarray

In [13]:
#one of the cons of array
numpy.array([1,2,3,4,'Lex'], dtype='i')

ValueError: invalid literal for int() with base 10: 'Lex'

In [14]:
import numpy as np #alias, for lazy people ;)

In [15]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [16]:
# Dimensions

In [17]:
[['M',1.8],['A',2],['J',3]]

[['M', 1.8], ['A', 2], ['J', 3]]

In [18]:
# Zero Dimension

In [21]:
zero = np.array(10)

In [25]:
zero.shape

()

In [23]:
# One dimension

In [24]:
one = np.array([10,11,12,13,14,15])

In [27]:
one.shape

(6,)

In [28]:
# Two dimensional

In [31]:
two = np.array([[10,11,12,13],[14,15,16,17]])

In [32]:
two.shape

(2, 4)

In [33]:
#Three dimesnional

In [34]:
three = np.array([ [[1,2,3],[4,5,6],[7,8,9]] ])

In [35]:
three.shape
#1: [[1,2,3],[4,5,6],[7,8,9]]
#3: [1,2,3],[4,5,6],[7,8,9]
#3 1,2,3

(1, 3, 3)

In [36]:
q_dimension = np.array([ [[1,2,3],[4,5,6],[7,8,9]], [[1,2,3],[4,5,6],[7,8,9]] ])

In [37]:
q_dimension.shape

(2, 3, 3)

In [38]:
#Operations on arrays

In [39]:
one[0]

10

In [40]:
one[1:3]

array([11, 12])

In [41]:
two[1][2]

16

In [42]:
two[1,2]

16

In [43]:
one

array([10, 11, 12, 13, 14, 15])

In [44]:
one[::2] #double colon, when we need to skip certain elements [start:end:step]

array([10, 12, 14])

In [45]:
one[:] #single colon means get all values

array([10, 11, 12, 13, 14, 15])

In [48]:
one[:2]

array([10, 11])

In [49]:
one[-1]

15

In [51]:
three.shape

(1, 3, 3)

In [50]:
three

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [52]:
three[0,2,1]

8

In [53]:
three[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
three[0,2]

array([7, 8, 9])

In [55]:
three[0,2,1]

8

In [57]:
three[0,2,1:] #or three[0,2,1:3]  

array([8, 9])

In [58]:
three[0,1,2]

6

In [60]:
# reshape the array

In [61]:
array1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [67]:
array1.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [68]:
array1.reshape(4,4)

ValueError: cannot reshape array of size 10 into shape (4,4)

In [69]:
array1.reshape(1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]])

In [70]:
# when you are not sure, what value should be there in place of 2nd dimension

In [71]:
array1.reshape(2,-1) #-1 will calculate what should be the ideal value of the 2nd dimension 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [72]:
array2 = array1.reshape(2,-1)

In [73]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [74]:
array2.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
flat_array = array2.reshape(-1)

In [75]:
# iterating through arrays

In [77]:
for i in flat_array:
    print(i)

1
2
3
4
5
6
7
8
9
10


In [78]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [79]:
len(array2)

2

In [80]:
for j in array2:
    print(j)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [81]:
array_with_nine_numbers = np.array([1,2,3,4,5,6,7,8,9])

In [83]:
array3 = array_with_nine_numbers.reshape(3,3)

In [84]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [85]:
for l in array3:
    print(l)

[1 2 3]
[4 5 6]
[7 8 9]


In [86]:
# how to access elements inside list of list/  multdimensional arrays

In [90]:
for j in array2:
    print(j) #j is nothing but a list
    for i in j:
        print(i)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [91]:
array3.shape

(3, 3)

In [94]:
for j in array3:
    for i in j:
        print(i)

1
2
3
4
5
6
7
8
9


In [95]:
(10)  #one dimensional - one loop
(10,10) #two dimesnional - two loops
(10,10,10) #three dimesnional -three loops

(10, 10, 10)

In [97]:
array3.reshape(1,3,3)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Assignment

#### Q1

In [100]:
# Give me every element of array4
#array4 = array3.reshape(1,3,3)

#### Q2

In [102]:
#Get the common elements between list1 and list2
#For eg: input from user=> list1= [2,3,4] list2=[3,4,5] (search on how to take list as an input from user, lets learn googling)
#output: [3,4]
#Hint: One might think to use *in* operator

#### Q3

In [103]:
#Try Q2 with numpy arrays instead of lists
# Also, google if there are any shortcuts (I mean any dedicated function to find intersection between two arrays/list)

#### Q4

In [104]:
# Remove the common elements of list1 from list2
#For eg: input=> list1=[2,3,4] list2 = [3,4,5]
#output: [2] #removed 3 and 4 since they were present in list2
#hint: *in* and remove function of list
#Try to perform the same with numpy array

#### Q5

In [105]:
# Add(append) elements to list1 from list2 if that element is not present already in list1.
#(I mean add the element which is not common)
# for eg: input => list1=[1,2,3,4,5] list2=[3,4,5,6,7]
#output=> [1,2,3,4,5,6,7] no need to add 3,4,5 again to list 1 since it is common
#hint: *not in* and append