In [21]:
import numpy as np

In [ ]:
# Give me every element of array4
#array4 = array3.reshape(1,3,3)

In [22]:
array = np.array([1,2,3,4,5,6,7,8,9]) 
array3 = array.reshape(3,3)
array4 = array3.reshape(1,3,3)

In [23]:
array4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [24]:
for i in array4:
    for x in i:
        for y in x:
            print(y)

1
2
3
4
5
6
7
8
9


In [ ]:
,#Get the common elements between list1 and list2
#For eg: input from user=> list1= [2,3,4] list2=[3,4,5] (search on how to take list as an input from user, lets learn googling)
#output: [3,4]
#Hint: One might think to use *in* operator,,

In [25]:
lst_1 = []
  
# number of elements as input
n = int(input("Enter number of elements : "))
  
# iterating till the range
for i in range(0, n):
    ele = int(input())
    # adding the element
    lst_1.append(ele)  
  
print(lst_1)

lst_2 = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst_2.append(ele)  
print(lst_2)

result = []
for element in lst_1:
    if element in lst_2:
        result.append(element)
print(result)


Enter number of elements : 5
1
2
3
4
5
[1, 2, 3, 4, 5]
Enter number of elements : 5
3
4
5
6
7
[3, 4, 5, 6, 7]
[3, 4, 5]


In [ ]:
#Try Q2 with numpy arrays instead of lists
# Also, google if there are any shortcuts (I mean any dedicated function to find intersection between two arrays/list)

In [26]:
print(np.intersect1d(lst_1, lst_2))


[3 4 5]


In [ ]:
## Remove the common elements of list1 from list2
#For eg: input=> list1=[2,3,4] list2 = [3,4,5]
#output: [2] #removed 3 and 4 since they were present in list2
#hint: *in* and remove function of list
#Try to perform the same with numpy array

In [27]:
lst_1 = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst_1.append(ele)  
print(lst_1)

lst_2 = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst_2.append(ele)  
print(lst_2)

result = lst_1 + lst_2
        
for element in result:
    if element in lst_1 and element in lst_2:
        lst_1.remove(element)
        lst_2.remove(element)
        result = lst_1 + lst_2
        
print(result)


Enter number of elements : 5
1
2
3
4
5
[1, 2, 3, 4, 5]
Enter number of elements : 5
3
4
5
6
7
[3, 4, 5, 6, 7]
[1, 2, 6, 7]


In [31]:
print(np.setdiff1d(lst_1, lst_2))


[1 2]


In [ ]:
# Add(append) elements to list1 from list2 if that element is not present already in list1.
#(I mean add the element which is not common)
# for eg: input => list1=[1,2,3,4,5] list2=[3,4,5,6,7]
#output=> [1,2,3,4,5,6,7] no need to add 3,4,5 again to list 1 since it is common
#hint: *not in* and append

In [5]:
lst_1 = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst_1.append(ele)  
print(lst_1)

lst_2 = []
n = int(input("Enter number of elements : "))
for i in range(0, n):
    ele = int(input())
    lst_2.append(ele)  
print(lst_2)

for element in lst_2:
    if element not in lst_1:
        lst_1.append(element)
print(lst_1)

Enter number of elements : 5
1
2
3
4
5
[1, 2, 3, 4, 5]
Enter number of elements : 5
3
4
5
6
7
[3, 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]


In [8]:
np.union1d(lst_1, lst_2)

array([1, 2, 3, 4, 5, 6, 7])